# Generated by Django 4.0.1 on 2022-01-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=256, unique=True)),
                ('color1', models.CharField(max_length=256)),
                ('color2', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('critterpedia_image', models.CharField(max_length=256)),
                ('icon_image', models.CharField(max_length=256)),
                ('furniture_image', models.CharField(max_length=256)),
                ('museum_description', models.CharField(max_length=1000)),
                ('catch_phrase', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('sell_price', models.IntegerField()),
                ('lighting_type', models.CharField(max_length=256)),
                ('shadow', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=256, unique=True)),
                ('color1', models.CharField(max_length=256)),
                ('color2', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('size', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('interactive', models.BooleanField()),
                ('can_reorder', models.BooleanField()),
                ('in_catalog', models.BooleanField()),
                ('museum_description', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=256, unique=True)),
                ('color1', models.CharField(max_length=256)),
                ('color2', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('critterpedia_image', models.CharField(max_length=256)),
                ('icon_image', models.CharField(max_length=256)),
                ('furniture_image', models.CharField(max_length=256)),
                ('museum_description', models.CharField(max_length=1000)),
                ('catch_phrase', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('sell_price', models.IntegerField()),
                ('weather', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=256, unique=True)),
                ('color1', models.CharField(max_length=256)),
                ('color2', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('icon_image', models.CharField(max_length=256)),
                ('house_image', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=256)),
                ('personality', models.CharField(max_length=256)),
                ('birthday', models.CharField(max_length=256)),
                ('catchphrase', models.CharField(max_length=256)),
                ('style1', models.CharField(max_length=256)),
                ('style2', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
