# Generated by Django 4.0.1 on 2022-01-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acnh_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('size', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('color1', models.CharField(max_length=256)),
                ('color2', models.CharField(max_length=256)),
                ('interactive', models.BooleanField()),
                ('can_reorder', models.BooleanField()),
                ('in_catalog', models.BooleanField()),
                ('museum_description', models.CharField(max_length=1000)),
                ('spreadsheet_id', models.CharField(max_length=256)),
            ],
        ),
    ]
